### ISSUE TITLE
A little help

### ISSUE THREAD

**Issue by ThoWmas31** [lon9/jewel-extractor#1]
Hello,

I'm not a developper, i install Go library + packr library but not i go this message  when i type : `C:\Projects\Go\bin>packr`

> C:\Projects\Go\bin>packr
> Error: FindFirstFile C:\Projects\Go\bin\jewel-extractor-master\unify-jewel-info\dist: The system cannot find the file specified.
> Usage:
>   packr [flags]
>   packr [command]
> 
> Available Commands:
>   build       Wraps the go build command with packr
>   clean       removes any *-packr.go files
>   help        Help about any command
>   install     Wraps the go install command with packr
>   version     prints packr version
> 
> Flags:
>   -z, --compress       compress box contents
>   -h, --help           help for packr
>   -i, --input string   path to scan for packr Boxes (default "C:\\Projects\\Go\\bin")
>   -v, --verbose        print verbose logging information
> 
> Use "packr [command] --help" for more information about a command.

Or when i type 

What i'm doing wrong ?

Great initiative for your project, just a little help for newbies likes me

**Comment by lon9** [comment]
@ThoWmas31 
I'm sorry, I forgot to add a file `unify-jewel-info/dist/decorations.json`. I updated repository, so you can build it after re-download it. Thank you for your information.

If you are using Windows 64bit, there is a executable at https://github.com/lon9/jewel-extractor/releases

**Comment by ThoWmas31** [comment]
Your Exe not work on my Win 10 pro X64 sir , i retry with your update repo
